server:
  port: 8888
spring:
  application:
    name: bootcamp-adventureworks-configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/soabel/bootcamp-adventureworks-localconfigrepo.git
          default-label: main
          timeout: 10
